fileVersion: 1
id: "3"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: SRC1
  WORK:
    database: BRYAN_DEV
    schema: DEV_STAGING
name: New Environment
type: Environment
