fileVersion: 1
id: "6"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: EXAMPLES
  WORK:
    database: BRYAN_DEV
    schema: DEV_STAGING
name: New Environment
type: Environment
